spring.datasource.url=jdbc:postgresql://localhost:5432/solicitudesdb
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

# donde vive la guia telefonica (Eureka)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${random.uuid}:${server.port}

eureka.instance.hostname=127.0.0.1
eureka.instance.prefer-ip-address=true